First entry for gsoc-jorge
poliastro/poliastro.github.io pull request #24
Opened 2019-05-10 11:40 UTC by jorgepiloto

This includes a markdown file about my gsoc experience :rocket:

2019-05-10 14:36 UTC, astrojuanlu requested changes
Some typos!

And in "my plans for this summer" I would include the things you will contribute to the project, rather than talking about how you will spend the money :)

2019-05-10 14:36 UTC, Juanlu001 commented on content/articles/2019-05-10-poliastro-gsoc-jorge.md
> +slug:_ 2019-05-10-poliastro-gsoc-jorge
Extra underscore?

2019-05-10 14:36 UTC, Juanlu001 commented on content/articles/2019-05-10-poliastro-gsoc-jorge.md
> +build and how the different modules talked among between them. I had no idea
```suggestion
built and how the different modules talked among them. I had no idea
```

2019-05-10 14:36 UTC, Juanlu001 commented on content/articles/2019-05-10-poliastro-gsoc-jorge.md
> +first pull request was wuite massive...
```suggestion
first pull request was massive...
```

2019-05-10 14:36 UTC, Juanlu001 commented on content/articles/2019-05-10-poliastro-gsoc-jorge.md
> +But after that I started feeling more confortable with GitHub_ and sphinx, the
```suggestion
But after that I started feeling more confortable with GitHub and Sphinx, the
```

2019-05-10 14:36 UTC, Juanlu001 commented on content/articles/2019-05-10-poliastro-gsoc-jorge.md
> +GSOC stippend is one of the main attractives for students when working in Open
```suggestion
GSOC stipend is one of the main attractions for students when working in Open
```

2019-05-10 16:13 UTC, jorgepiloto commented
It is quite strange that `_` appears... It does not show on my editor. Let me check with another one.

2019-05-13 10:08 UTC, astrojuanlu approved these changes

2019-05-13 10:08 UTC, merged