Improve webpage navbar and home-page
poliastro/poliastro.github.io pull request #45
Opened 2020-04-06 08:00 UTC by jorgepiloto

As discussed privately, this tries to solve for https://github.com/poliastro/poliastro/issues/712, which was opened in order to have a better front page. 

At first, I created a for loop which iterated over all the different created pages. This was nice and simple but the problem came when linking those pages to the actual external content. This implementation enables maintainers to just modify the URLs in the actual `pelicanconfig.py` to redirect.

Some tasks still need to be solved:

- [x] Menu bar is completed
- [ ] Home page with content
- [ ] Show all posts in blog page

2020-04-06 08:41 UTC, jorgepiloto commented
With the new update on blog location, last task is solved :heart_eyes:

2020-04-08 14:59 UTC, jorgepiloto commented
The image below shows the looking this PR will impose on the actual web page. Notice that the `home` content is not completed, it was just a draft idea.

![web](https://user-images.githubusercontent.com/28702884/78799339-48c57700-79ba-11ea-8825-726b0e9f96a9.png)

2020-04-08 15:11 UTC, astrojuanlu requested changes
This is great improvement over what we have now, and I am glad to merge it! After that we can:

* Address some infrastructure changes that I will detail in a separate issue
* Add more content here

Just left a couple of comments.

2020-04-08 15:11 UTC, astrojuanlu commented on content/pages/home.rst
> +Welcome to poliastro webpage
```suggestion
poliastro - Astrodynamics in Python
```

2020-04-08 15:11 UTC, astrojuanlu commented on content/pages/home.rst
> +A little brief description on the project and the website...?
Your suggestion presented in the screen capture looks OK for now!

2020-04-08 18:07 UTC, shreyasbapat commented
Can we have just a `pip install poliastro` over there?  Wil look nice :p

2020-04-08 18:11 UTC, astrojuanlu commented
Great catch @shreyasbapat !

2020-04-08 18:13 UTC, shreyasbapat commented
@astrojuanlu Can we change our docs theme also?  :crying_cat_face:  

(I know the answer is no, but still :p)

2020-04-08 18:41 UTC, jorgepiloto commented on content/pages/home.rst
> +Welcome to poliastro webpage
Solved :+1:

2020-04-08 18:42 UTC, astrojuanlu commented
@shreyasbapat no :) sphinx-rtd-theme is, with all its problems, the best Sphinx theme available out there, nowadays. Sure, I'd like them to do more active maintenance... But I am sure they will pay more attention to it soon :)

2021-01-24 10:38 UTC, astrojuanlu commented
@jorgepiloto What's the status of this? :)

2021-02-13 18:40 UTC, astrojuanlu commented
Update: we fixed some local issues and this is almost ready to go 🚀

2021-02-14 11:13 UTC, jorgepiloto commented
This is ready by my side @astrojuanlu!

2021-02-14 11:29 UTC, astrojuanlu commented
This looks wonderful @jorgepiloto ! 😍 I'm so happy about this update, now we can promote this as the actual poliastro website rather than its documentation.

Merging and deploying the changes!

2021-02-14 11:30 UTC, astrojuanlu approved these changes

2021-02-14 11:30 UTC, merged

2021-02-14 11:41 UTC, jorgepiloto commented
I'm glad you like it! It is already deployed and working as expected :rocket: